core/account/urls.py
from django.urls import path
from . import views


app_name = 'account'

urlpatterns = [
    path('register/', views.UserRegistrationView.as_view(), name='user-register'),
    path('verify_register_code/', views.CodeVerificationRegisterView.as_view(), name='verify-register-code'),
    path('verify_login_code/', views.CodeVerificationLoginView.as_view(), name='verify-login-code'),
    path('login/', views.UserLoginView.as_view(), name='user-login'),
    path('logout/', views.UserLogoutView.as_view(), name='user-logout'),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('account/', include('account.urls', namespace='account')),
    path('order/', include('order.urls', namespace='order')),
    path('products/', include('product.urls', namespace='product')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('api-auth/', include('rest_framework.urls')),
    path('api-v1/product/', include('product.api.v1.urls', namespace='product_api')),
    path('api-v1/account/', include('account.api.v1.urls', namespace='account_api')),
    path('api-v1/order/', include('order.api.v1.urls', namespace='order_api')),

    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    path('swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/home/urls.py
from django.urls import path
from . import views


app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home-page'),
    path('category/<slug:category_slug>', views.HomeView.as_view(), name='category-filter'),
]

core/order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('create/', views.OrderCreateView.as_view(), name='order-create'),
    path('list/', views.OrderListView.as_view(), name='order-list'),
    path('details/<int:order_id>/', views.OrderDetailsView.as_view(), name='order-details'),
    path('coupon/<int:order_id>/', views.CouponApplyView.as_view(), name='apply-coupon'),

    path('cart/', views.CartView.as_view(), name='cart-page'),
    path('cart/add/<int:variant_id>/', views.AddCartView.as_view(), name='add-cart'),
    path('cart/remove/<int:product_id>/', views.RemoveCartView.as_view(), name='remove-cart'),
]

core/templates/inc/messages.html
{% if messages %}
  {% for msg in messages %}
    <p class="alert alert-{{msg.tags}} col-md-6">{{msg}}</p>
  {% endfor %}
{% endif %}

core/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="{% url 'home:home-page' %}">
          Home {% if request.user.is_authenticated %} ({{ request.user.email }})  {% endif %}</a>
          {% if request.user.is_authenticated %}
            <a class="nav-link active" aria-current="page" href="{% url 'account:user-logout' %}">Logout</a>
            <a class="nav-link active" aria-current="page" href="{% url 'order:order-list' %}">Orders</a>
          {% else%}
          <a class="nav-link active" aria-current="page" href="{% url 'account:user-register' %}">Register</a>
          <a class="nav-link active" aria-current="page" href="{% url 'account:user-login' %}">Login</a>
          {% endif %}
          <a class="nav-link active" aria-current="page" href="{% url 'order:cart-page' %}">Cart({{ cart | length }})</a>
      </div>
  </div>
</nav>